### ISSUE TITLE
"The Rust Programming Language" Buch

### ISSUE THREAD

**Issue by UniqueActive** [scy/advent-of-code#2]
Wollte das nur als Anregung hier lassen, weil ich kein Discord nutze:

An einigen Stellen sagst du, dass die dich in Rust by Example ziemlich ins tiefe Wasser werfen, und einige Dinge nicht erklären. Wenn du zu einem Thema verwirrt bist, und eine bessere Beschreibung haben willst, dann empfehle ich das [Rust Buch](https://doc.rust-lang.org/book/), bei dem du dann einfach zu irgendeinem Thema im Inhaltsverzeichnis zum entsprechenden Abschnitt springen kannst, um genauere Basisinformatioen zu bekommen.

Das kann ganz praktisch sein, wenn man mal in Rust by Example nicht weiterkommt, da das Rust Buch auch eigentlich mehr für komplette Rust-Anfänger gedacht ist.

**Comment by scy** [comment]
Danke dir (im Nachhinein) für die Info. Du warst nicht die einzige Person, die diese Anmerkung hatte, und ich hab das Rust-Buch dann auch teilweise benutzt. Ich denke, ich war einfach schlecht vorbereitet und hatte gehofft, dass mir Rust by Example reicht. ;)
